---
title: "Brain Canada Project Analysis"
author: "Yavuz Shahzad"
date: "5/16/2024"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
library(knitr)

opts_chunk$set(tidy.opts=list(width.cutoff=60),tidy=TRUE)

BC_Rot <- read.csv("~/Desktop/Brain Canada Project/Data Analysis/BrainCanadaFinalRotated.csv")
BC_Or <- read.csv("~/Desktop/Brain Canada Project/Data Analysis/BrainCanada.csv")

holm_bonferroni <- function(T3, T2, T1){
  
  suppressWarnings({
  first <- wilcox.test(T3, T2, paired = TRUE)
  second <- wilcox.test(T3, T1, paired = TRUE)
  third <- wilcox.test(T2, T1, paired = TRUE)
  })
  
  p_vals <- c(first$p.value, second$p.value, third$p.value)
  names(p_vals) <- c("T3 vs T2", "T3 vs T1", "T2 vs T1")
  sorted_p_vals <- sort(p_vals)
  
  exit <- FALSE
  result <- c()
  
  for (k in 1:3){
    if (!(exit)) {
      if (sorted_p_vals[k] < (0.05/(3 + 1 - k))){
        result <- append(result, "Reject")
      }
      
      else{
        result <- append(result, "Fail to reject")
        exit <- TRUE
      }
    }
    
    else{
      result <- append(result, "Fail to reject")
    }
  }
  cat("\n")
  print("Results of pairwise, paired Wilcoxon with Holm-Bonferroni correction for multiple comparisons")
  cat("\n")
  print(sorted_p_vals)
  cat("\n")
  print(result)
  
}

bootstrap_CI <- function(TIME1, TIME2) {
  
  B <- 10000 #Ten thousand re-samples
  difference <- TIME2 - TIME1
  bootMean <- vector()
  
  for (i in 1:B){
    bootSample <- sample(difference, size = 25,
                         replace = TRUE)
    
    #Assigns mean values of each resample to the vector bootMean
    bootMean[i] <- mean(bootSample)
    #cat("Bootstrap sample:", i ,"\n")
  }
  
  mean(bootMean)
  
  #Lends a confidence interval, since this is an approximate sample distribution.
  CI <- quantile(bootMean, probs = c(0.025, 0.975))
  
  return(CI)
}


interaction_plot <- function(){
  interaction.plot(x.factor = data$exercise, #x-axis variable
                 trace.factor = data$gender, #variable for lines
                 response = data$weight_loss, #y-axis variable
                 fun = median, #metric to plot
                 ylab = "Weight Loss",
                 xlab = "Exercise Intensity",
                 col = c("pink", "blue"),
                 lty = 1, #line type
                 lwd = 2, #line width
                 trace.label = "Gender")
}
knitr::opts_chunk$set(echo = TRUE)
```

$\\$
\textbf{FMA}

```{r}

FMA_MANOVA <- aov(FMA ~ MEP_Group + Follow_Up + MEP_Group*Follow_Up + 
                   FMA_baseline , data = BC_Rot)
summary(FMA_MANOVA)

holm_bonferroni(BC_Or$FMA_T3, BC_Or$FMA_T2, BC_Or$FMA_T1)


interaction.plot(x.factor = BC_Rot$Follow_Up, #x-axis variable
                 trace.factor = BC_Rot$MEP_Group, #variable for lines
                 response = BC_Rot$FMA, #y-axis variable
                 fun = median, #metric to plot
                 ylab = "FMA",
                 xlab = "Follow Up",
                 col = c("pink", "blue"),
                 trace.label = "MEP Group")

bootstrap_CI(BC_Or$FMA_T1, BC_Or$FMA_T3)
bootstrap_CI(BC_Or$FMA_T2, BC_Or$FMA_T3)
bootstrap_CI(BC_Or$FMA_T1, BC_Or$FMA_T2)
```
$\\$

$\\$
\textbf{BBT}

```{r}
BBT_MANOVA <- aov(BBT ~ MEP_Group + Follow_Up
                  + MEP_Group*Follow_Up + BBT_Baseline, data = BC_Rot)

summary(BBT_MANOVA)

holm_bonferroni(BC_Or$BBT_T3_A, BC_Or$BBT_T2_A, BC_Or$BBT_T1_A)

bootstrap_CI(BC_Or$BBT_T1_A, BC_Or$BBT_T3_A)
bootstrap_CI(BC_Or$BBT_T2_A, BC_Or$BBT_T3_A)
bootstrap_CI(BC_Or$BBT_T1_A, BC_Or$BBT_T2_A)
```
$\\$
$\\$
\textbf{Grip Strength}

```{r}
GS_MANOVA <- aov(Grip_Strength ~ MEP_Group + Follow_Up + MEP_Group*Follow_Up 
                 + GS_Baseline, data = BC_Rot)
summary(GS_MANOVA)
holm_bonferroni(BC_Or$GS_T3_A, BC_Or$GS_T2_A, BC_Or$GS_T1_A)

bootstrap_CI(BC_Or$GS_T1_A, BC_Or$GS_T3_A)
bootstrap_CI(BC_Or$GS_T1_A, BC_Or$GS_T2_A)
bootstrap_CI(BC_Or$GS_T2_A, BC_Or$GS_T3_A)
```
$\\$
$\\$
\textbf{MAL AOU}

```{r}
MAL_AOU_MANOVA <- aov(MAL_AOU ~ MEP_Group + Follow_Up + MEP_Group*Follow_Up 
                      + MAL_AOU_Baseline, data = BC_Rot)
summary(MAL_AOU_MANOVA)
holm_bonferroni(BC_Or$MAL_Quant_T3, BC_Or$MAL_Quant_T2, BC_Or$MAL_Quant_T1)

bootstrap_CI(BC_Or$MAL_Quant_T2, BC_Or$MAL_Quant_T3)
bootstrap_CI(BC_Or$MAL_Quant_T1, BC_Or$MAL_Quant_T3)
bootstrap_CI(BC_Or$MAL_Quant_T1, BC_Or$MAL_Quant_T2)

```
$\\$

$\\$
\textbf{MAL QOU}
```{r}
MAL_QOU_MANOVA <- aov(MAL_QOU ~ MEP_Group + Follow_Up + MEP_Group*Follow_Up 
                      + MAL_QOU_Baseline, data = BC_Rot)
summary(MAL_QOU_MANOVA)

holm_bonferroni(BC_Or$MAL_Quali_T3, BC_Or$MAL_Quali_T2, BC_Or$MAL_Quali_T1)

wilcox.test(BC_Or$MAL_Quali_T3, BC_Or$MAL_Quali_T2, BC_Or$MAL_Quali_T1, paird = TRUE)

bootstrap_CI(BC_Or$MAL_Quali_T1, BC_Or$MAL_Quali_T3)
bootstrap_CI(BC_Or$MAL_Quali_T1, BC_Or$MAL_Quali_T2)
bootstrap_CI(BC_Or$MAL_Quali_T2, BC_Or$MAL_Quali_T3)
```
$\\$
$\\$
\textbf{Shoulder Active ROM}

```{r}
Shoulder_MANOVA <- aov(BC_Rot$Shoulder_AROM ~ MEP_Group + Follow_Up 
                       + MEP_Group*Follow_Up + Shoulder_AROM_Baseline, data = BC_Rot)
summary(Shoulder_MANOVA)

holm_bonferroni(BC_Or$ROM_Shoulder_Affected_Active_T3,
                BC_Or$ROM_Shoulder_Affected_Active_T2, 
                BC_Or$ROM_Shoulder_Affected_Active_T1)

interaction.plot(x.factor = BC_Rot$Follow_Up, #x-axis variable
                 trace.factor = BC_Rot$MEP_Group, #variable for lines
                 response = BC_Rot$Shoulder_AROM, #y-axis variable
                 fun = median, #metric to plot
                 ylab = "Shoulder Active ROM",
                 xlab = "Follow Up",
                 col = c("pink", "blue"),
                 trace.label = "MEP Group")

bootstrap_CI(BC_Or$ROM_Shoulder_Affected_Active_T2, BC_Or$ROM_Shoulder_Affected_Active_T3)
bootstrap_CI(BC_Or$ROM_Shoulder_Affected_Active_T1, BC_Or$ROM_Shoulder_Affected_Active_T3)
bootstrap_CI(BC_Or$ROM_Shoulder_Affected_Active_T1, BC_Or$ROM_Shoulder_Affected_Active_T2)

```
$\\$
$\\$
\textbf{Elbow Active ROM}
```{r}
Elbow_MANOVA <- aov(BC_Rot$Elbow_AROM ~ MEP_Group + Follow_Up
                    + MEP_Group*Follow_Up + Elbow_AROM_baseline, data = BC_Rot)
summary(Elbow_MANOVA)

holm_bonferroni(BC_Or$ROM_Elbow_Affected_Active_T3,
                BC_Or$ROM_Elbow_Affected_Active_T2, 
                BC_Or$ROM_Elbow_Affected_Active_T1)

bootstrap_CI(BC_Or$ROM_Elbow_Affected_Active_T2, BC_Or$ROM_Elbow_Affected_Active_T3)
bootstrap_CI(BC_Or$ROM_Elbow_Affected_Active_T1, BC_Or$ROM_Elbow_Affected_Active_T3)
bootstrap_CI(BC_Or$ROM_Elbow_Affected_Active_T1, BC_Or$ROM_Elbow_Affected_Active_T2)
```
$\\$
$\\$
\textbf{Wrist Active ROM}
```{r}
Wrist_MANOVA <- aov(BC_Rot$Wrist_AROM ~ MEP_Group + Follow_Up 
                    + MEP_Group*Follow_Up + Wrist_AROM_Baseline, data = BC_Rot)
summary(Wrist_MANOVA)

holm_bonferroni(BC_Or$ROM_Wrist_Affected_Active_T3,
                BC_Or$ROM_Wrist_Affected_Active_T2, 
                BC_Or$ROM_Wrist_Affected_Active_T1)

bootstrap_CI(BC_Or$ROM_Wrist_Affected_Active_T2, BC_Or$ROM_Wrist_Affected_Active_T3)
bootstrap_CI(BC_Or$ROM_Wrist_Affected_Active_T1, BC_Or$ROM_Wrist_Affected_Active_T3)
bootstrap_CI(BC_Or$ROM_Wrist_Affected_Active_T1, BC_Or$ROM_Wrist_Affected_Active_T2)
```
$\\$
$\\$
